name: Pytest with ProgresSQL

on:
  push:
    paths:
      - 'tests/api/**'
      - 'src/**'
      - '.github/workflows/pytest.yml'
  pull_request:
    paths:
      - 'tests/api/**'
    
jobs: 
    test: 
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: Start Docker Compose services
              run: docker-compose up -d

            - name: install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

              env:
                DB_HOST: localhost
                DB_PORT: 5432
                DB_USER: postgres
                DB_PASSWORD: postgres
                DB_NAME: testdb
            
            - name: Show Postgres Logs (if failure)
              if: failure()
              run: docker-compose logs postgres

            - name: Tear down Docker Compose services
              if: always()
              run: docker-compose down
                
            - name: Run API Tests
              run: |
                pytest tests/api/ -v --html=report.html --self-contained-html

            - name: Upload Report
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: report.html